Function getMainQuery(grouping As String, month As String, year As String, bd As String, sd As String, sr As String, pb As String, vp As String) As String
	Dim query As String
	query = "SELECT   " 
	query = query & "CASE WHEN (sc.spend_base_seq IN (1, 2, 3, 4, 5))THEN 'Distributor' "
	query = query & "     WHEN (sc.spend_base_seq = 6)THEN 'Operator' "
	query = query & "END AS businessunit, "
	query = query & "CASE WHEN (md.FISCAL_MONTH_NUMBER = (:p_Month))THEN SUM (epf.expense_amt) "
	query = query & "END AS monthexpense_amt, "
	query = query & "0 AS monthpounds, "
	query = query & "0 AS monthnetreceivables, "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "INITCAP (mpbd.business_division_descr) AS businessdivisiondescr, "
	query = query & "sc.spend_base_descr, "
	query = query & "sc.spend_base_seq, "
	query = query & "sc.spend_subcategory_descr, "
	query = query & "sc.spend_subcategory_seq, "
	query = query & "md.year_descr, "
	query = query & "md.month_descr, "
	query = query & "SUM (epf.expense_amt) AS expense_amt, "
	query = query & "0 AS total_pounds_shipped, "
	query = query & "0 AS net_receivable_dollar "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd, "
	query = query & "tdw_owner.expense_payment_fact epf, "
	query = query & "tdw_owner.fsv_spend_category sc, "
	query = query & "tdw_owner.restated_market m, "
	query = query & "tdw_owner.month_dim md, "
	query = query & "tdw_owner.restated_product p, "
	query = query & "tdw_owner.acct_dim a, "
	query = query & "tdw_owner.expense_type et, "
	query = query & "tdw_owner.spend_request_dim s, "
	query = query & "tdw_owner.operator_dim o, "
	query = query & "tdw_owner.day_dim d1, "
	query = query & "tdw_owner.day_dim d2, "
	query = query & "tdw_owner.expense_attribute_dim ead, "
	query = query & "tdw_owner.expense_payee_dim pay, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE mpbd.restated_mkt_prd_bus_div_key = epf.restated_mkt_prd_bus_div_key "
	query = query & "AND epf.expense_type_key = sc.expense_type_key "
	query = query & "AND epf.acct_key = sc.acct_key "
	query = query & "AND epf.restated_market_key = m.restated_market_key "
	query = query & "AND epf.month_key = md.month_key "
	query = query & "AND epf.restated_product_key = p.restated_product_key "
	query = query & "AND epf.acct_key = a.acct_key "
	query = query & "AND epf.expense_type_key = et.expense_type_key "
	query = query & "AND epf.spend_request_key = s.spend_request_key "
	query = query & "AND epf.operator_key = o.operator_key "
	query = query & "AND epf.report_period_begin_day_key = d1.day_key "
	query = query & "AND epf.report_period_end_day_key = d2.day_key "
	query = query & "AND epf.expense_attribute_key = ead.expense_attribute_key "
	query = query & "AND epf.expense_payee_key = pay.expense_payee_key "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m.DIVISION_CODE "
	query = query & "AND sc.spend_base_seq <> 0 "
	query = query & "AND sc.spend_subcategory_seq <> 0 "
	query = query & "AND (mpbd.business_division_code IN ('F01', 'F03', 'F04', 'F08', 'F15')) "
	query = query & "AND (m.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md.year_descr IN (:p_year)) "
	query = query & "and md.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m.division_code IN (:p_salesdivision)) "
	query = query & "AND (m.region_code IN (:p_salesregion)) "
	query = query & "AND (m.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY  "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "INITCAP (mpbd.business_division_descr), "
	query = query & "sc.spend_base_descr, "
	query = query & "sc.spend_base_seq, "
	query = query & "sc.spend_subcategory_descr, "
	query = query & "sc.spend_subcategory_seq, "
	query = query & "md.year_descr, "
	query = query & "md.month_descr, "
	query = query & "md.FISCAL_MONTH_NUMBER "
	query = query & "---Add Expense Total Value Added "
	query = query & "UNION "
	query = query & "SELECT    "
	query = query & "CASE WHEN (sc.spend_base_seq IN (1, 2, 3, 4, 5))THEN 'Distributor' "
	query = query & "     WHEN (sc.spend_base_seq = 6)THEN 'Operator' "
	query = query & "END AS businessunit, "
	query = query & "CASE WHEN (md.FISCAL_MONTH_NUMBER = (:p_Month))THEN SUM (epf.expense_amt) "
	query = query & "END AS monthexpense_amt, "
	query = query & "0 AS monthpounds, "
	query = query & "0 AS monthnetreceivables, "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "'Total Value Added' AS businessdivisiondescr, "
	query = query & "sc.spend_base_descr, "
	query = query & "sc.spend_base_seq, "
	query = query & "sc.spend_subcategory_descr, "
	query = query & "sc.spend_subcategory_seq, "
	query = query & "md.year_descr, "
	query = query & "md.month_descr, "
	query = query & "SUM (epf.expense_amt) AS expense_amt, "
	query = query & "0 AS total_pounds_shipped, "
	query = query & "0 AS net_receivable_dollar "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd, "
	query = query & "tdw_owner.expense_payment_fact epf, "
	query = query & "tdw_owner.fsv_spend_category sc, "
	query = query & "tdw_owner.restated_market m, "
	query = query & "tdw_owner.month_dim md, "
	query = query & "tdw_owner.restated_product p, "
	query = query & "tdw_owner.acct_dim a, "
	query = query & "tdw_owner.expense_type et, "
	query = query & "tdw_owner.spend_request_dim s, "
	query = query & "tdw_owner.operator_dim o, "
	query = query & "tdw_owner.day_dim d1, "
	query = query & "tdw_owner.day_dim d2, "
	query = query & "tdw_owner.expense_attribute_dim ead, "
	query = query & "tdw_owner.expense_payee_dim pay, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE mpbd.restated_mkt_prd_bus_div_key = epf.restated_mkt_prd_bus_div_key "
	query = query & "AND epf.expense_type_key = sc.expense_type_key "
	query = query & "AND epf.acct_key = sc.acct_key "
	query = query & "AND epf.restated_market_key = m.restated_market_key "
	query = query & "AND epf.month_key = md.month_key "
	query = query & "AND epf.restated_product_key = p.restated_product_key "
	query = query & "AND epf.acct_key = a.acct_key "
	query = query & "AND epf.expense_type_key = et.expense_type_key "
	query = query & "AND epf.spend_request_key = s.spend_request_key "
	query = query & "AND epf.operator_key = o.operator_key "
	query = query & "AND epf.report_period_begin_day_key = d1.day_key "
	query = query & "AND epf.report_period_end_day_key = d2.day_key "
	query = query & "AND epf.expense_attribute_key = ead.expense_attribute_key "
	query = query & "AND epf.expense_payee_key = pay.expense_payee_key "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m.DIVISION_CODE "
	query = query & "AND sc.spend_base_seq <> 0 "
	query = query & "AND sc.spend_subcategory_seq <> 0 "
	query = query & "AND (mpbd.business_division_code IN ('F01','F08', 'F15')) "
	query = query & "AND (m.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md.year_descr IN (:p_year)) "
	query = query & "and md.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m.division_code IN (:p_salesdivision)) "
	query = query & "AND (m.region_code IN (:p_salesregion)) "
	query = query & "AND (m.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY  "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "'Total Value Added' , "
	query = query & "sc.spend_base_descr, "
	query = query & "sc.spend_base_seq, "
	query = query & "sc.spend_subcategory_descr, "
	query = query & "sc.spend_subcategory_seq, "
	query = query & "md.year_descr, "
	query = query & "md.month_descr, "
	query = query & "md.FISCAL_MONTH_NUMBER, "
	query = query & "mpbd.business_division_Descr "
	query = query & "--Begin Expense Total Market/CVP "
	query = query & "UNION "
	query = query & "SELECT    "
	query = query & "CASE WHEN (sc.spend_base_seq IN (1, 2, 3, 4, 5))THEN 'Distributor' "
	query = query & "     WHEN (sc.spend_base_seq = 6)THEN 'Operator' "
	query = query & "END AS businessunit, "
	query = query & "CASE WHEN (md.FISCAL_MONTH_NUMBER = (:p_Month))THEN SUM (epf.expense_amt) "
	query = query & "END AS monthexpense_amt, "
	query = query & "0 AS monthpounds, "
	query = query & "0 AS monthnetreceivables, "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "'Total Market/CVP' AS businessdivisiondescr, "
	query = query & "sc.spend_base_descr, "
	query = query & "sc.spend_base_seq, "
	query = query & "sc.spend_subcategory_descr, "
	query = query & "sc.spend_subcategory_seq, "
	query = query & "md.year_descr, "
	query = query & "md.month_descr, "
	query = query & "SUM (epf.expense_amt) AS expense_amt, "
	query = query & "0 AS total_pounds_shipped, "
	query = query & "0 AS net_receivable_dollar "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd, "
	query = query & "tdw_owner.expense_payment_fact epf, "
	query = query & "tdw_owner.fsv_spend_category sc, "
	query = query & "tdw_owner.restated_market m, "
	query = query & "tdw_owner.month_dim md, "
	query = query & "tdw_owner.restated_product p, "
	query = query & "tdw_owner.acct_dim a, "
	query = query & "tdw_owner.expense_type et, "
	query = query & "tdw_owner.spend_request_dim s, "
	query = query & "tdw_owner.operator_dim o, "
	query = query & "tdw_owner.day_dim d1, "
	query = query & "tdw_owner.day_dim d2, "
	query = query & "tdw_owner.expense_attribute_dim ead, "
	query = query & "tdw_owner.expense_payee_dim pay, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE mpbd.restated_mkt_prd_bus_div_key = epf.restated_mkt_prd_bus_div_key "
	query = query & "AND epf.expense_type_key = sc.expense_type_key "
	query = query & "AND epf.acct_key = sc.acct_key "
	query = query & "AND epf.restated_market_key = m.restated_market_key "
	query = query & "AND epf.month_key = md.month_key "
	query = query & "AND epf.restated_product_key = p.restated_product_key "
	query = query & "AND epf.acct_key = a.acct_key "
	query = query & "AND epf.expense_type_key = et.expense_type_key "
	query = query & "AND epf.spend_request_key = s.spend_request_key "
	query = query & "AND epf.operator_key = o.operator_key "
	query = query & "AND epf.report_period_begin_day_key = d1.day_key "
	query = query & "AND epf.report_period_end_day_key = d2.day_key "
	query = query & "AND epf.expense_attribute_key = ead.expense_attribute_key "
	query = query & "AND epf.expense_payee_key = pay.expense_payee_key "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m.DIVISION_CODE "
	query = query & "AND sc.spend_base_seq <> 0 "
	query = query & "AND sc.spend_subcategory_seq <> 0 "
	query = query & "AND (mpbd.business_division_code IN ('F03', 'F04')) "
	query = query & "AND (m.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md.year_descr IN (:p_year)) "
	query = query & "and md.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m.division_code IN (:p_salesdivision)) "
	query = query & "AND (m.region_code IN (:p_salesregion)) "
	query = query & "AND (m.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY  "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "'Total Market/CVP', "
	query = query & "sc.spend_base_descr, "
	query = query & "sc.spend_base_seq, "
	query = query & "sc.spend_subcategory_descr, "
	query = query & "sc.spend_subcategory_seq, "
	query = query & "md.year_descr, "
	query = query & "md.month_descr, "
	query = query & "md.FISCAL_MONTH_NUMBER, "
	query = query & "mpbd.business_division_Descr "
	query = query & "--Begin Expense TotalCustomer "
	query = query & "UNION "
	query = query & "SELECT    "
	query = query & "CASE WHEN (sc.spend_base_seq IN (1, 2, 3, 4, 5))THEN 'Distributor' "
	query = query & "     WHEN (sc.spend_base_seq = 6)THEN 'Operator' "
	query = query & "END AS businessunit, "
	query = query & "CASE WHEN (md.FISCAL_MONTH_NUMBER = (:p_Month))THEN SUM (epf.expense_amt) "
	query = query & "END AS monthexpense_amt, "
	query = query & "0 AS monthpounds, "
	query = query & "0 AS monthnetreceivables, "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "'Total Customer' AS businessdivisiondescr, "
	query = query & "sc.spend_base_descr, "
	query = query & "sc.spend_base_seq, "
	query = query & "sc.spend_subcategory_descr, "
	query = query & "sc.spend_subcategory_seq, "
	query = query & "md.year_descr, "
	query = query & "md.month_descr, "
	query = query & "SUM (epf.expense_amt) AS expense_amt, "
	query = query & "0 AS total_pounds_shipped, "
	query = query & "0 AS net_receivable_dollar "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd, "
	query = query & "tdw_owner.expense_payment_fact epf, "
	query = query & "tdw_owner.fsv_spend_category sc, "
	query = query & "tdw_owner.restated_market m, "
	query = query & "tdw_owner.month_dim md, "
	query = query & "tdw_owner.restated_product p, "
	query = query & "tdw_owner.acct_dim a, "
	query = query & "tdw_owner.expense_type et, "
	query = query & "tdw_owner.spend_request_dim s, "
	query = query & "tdw_owner.operator_dim o, "
	query = query & "tdw_owner.day_dim d1, "
	query = query & "tdw_owner.day_dim d2, "
	query = query & "tdw_owner.expense_attribute_dim ead, "
	query = query & "tdw_owner.expense_payee_dim pay, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE mpbd.restated_mkt_prd_bus_div_key = epf.restated_mkt_prd_bus_div_key "
	query = query & "AND epf.expense_type_key = sc.expense_type_key "
	query = query & "AND epf.acct_key = sc.acct_key "
	query = query & "AND epf.restated_market_key = m.restated_market_key "
	query = query & "AND epf.month_key = md.month_key "
	query = query & "AND epf.restated_product_key = p.restated_product_key "
	query = query & "AND epf.acct_key = a.acct_key "
	query = query & "AND epf.expense_type_key = et.expense_type_key "
	query = query & "AND epf.spend_request_key = s.spend_request_key "
	query = query & "AND epf.operator_key = o.operator_key "
	query = query & "AND epf.report_period_begin_day_key = d1.day_key "
	query = query & "AND epf.report_period_end_day_key = d2.day_key "
	query = query & "AND epf.expense_attribute_key = ead.expense_attribute_key "
	query = query & "AND epf.expense_payee_key = pay.expense_payee_key "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m.DIVISION_CODE "
	query = query & "AND sc.spend_base_seq <> 0 "
	query = query & "AND sc.spend_subcategory_seq <> 0 "
	query = query & "AND (mpbd.business_division_code IN ('F01', 'F03', 'F04', 'F08', 'F15')) "
	query = query & "AND (m.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md.year_descr IN (:p_year)) "
	query = query & "and md.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m.division_code IN (:p_salesdivision)) "
	query = query & "AND (m.region_code IN (:p_salesregion)) "
	query = query & "AND (m.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY  "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "'Total Customer', "
	query = query & "sc.spend_base_descr, "
	query = query & "sc.spend_base_seq, "
	query = query & "sc.spend_subcategory_descr, "
	query = query & "sc.spend_subcategory_seq, "
	query = query & "md.year_descr, "
	query = query & "md.month_descr, "
	query = query & "md.FISCAL_MONTH_NUMBER, "
	query = query & "mpbd.business_division_Descr "
	query = query & " "
	query = query & "--Begin Volume "
	query = query & "UNION "
	query = query & "SELECT   'zzz' AS businessunit, "
	query = query & "0 AS monthexpense_amt, "
	query = query & "CASE WHEN (ids_mf.FISCAL_MONTH_NUMBER = (:p_Month)) "
	query = query & "     THEN SUM (  ids_mf.mf_pounds_shipped "
	query = query & "               + ids_mf.mf_adjusted_pounds_shipped "
	query = query & "                + ids_mf.ids_pounds_shipped) "
	query = query & "END AS monthpounds, "
	query = query & "CASE WHEN (ids_mf.FISCAL_MONTH_NUMBER = (:p_Month)) "
	query = query & "     THEN SUM (  ids_mf.mf_gross_sales_amount "
	query = query & "               - ids_mf.mf_allow_amount "
	query = query & "               - ids_mf.mf_off_invoice_amount "
	query = query & "               + ids_mf.mf_revenue_adjustment "
	query = query & "               + ids_mf.ids_indirect_sales_amount) "
	query = query & "END AS monthnetreceivables, "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "INITCAP (mpbd.business_division_descr) AS businessdivisiondescr, "
	query = query & "NULL AS spend_base_descr, "
	query = query & "NULL AS spend_base_seq, "
	query = query & "NULL AS spend_subcategory_descr, "
	query = query & "NULL AS spend_subcategory_seq, "
	query = query & "ids_mf.year_descr, "
	query = query & "ids_mf.month_descr, "
	query = query & "0 AS expense_amt, "
	query = query & "SUM (  ids_mf.mf_pounds_shipped "
	query = query & "       + ids_mf.mf_adjusted_pounds_shipped "
	query = query & "       + ids_mf.ids_pounds_shipped "
	query = query & "       ) AS total_pounds_shipped, "
	query = query & "SUM (  ids_mf.mf_gross_sales_amount "
	query = query & "       - ids_mf.mf_allow_amount "
	query = query & "       - ids_mf.mf_off_invoice_amount "
	query = query & "       + ids_mf.mf_revenue_adjustment "
	query = query & "       + ids_mf.ids_indirect_sales_amount "
	query = query & "       ) AS net_receivable_dollar "
	query = query & "FROM (SELECT   mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER, "
	query = query & "SUM (mf.pounds_shipped) AS mf_pounds_shipped, "
	query = query & "SUM (mf.adj_pounds_shipped) AS mf_adjusted_pounds_shipped, "
	query = query & "SUM (mf.gross_sales_amount) AS mf_gross_sales_amount, "
	query = query & "SUM (mf.allow_amount) AS mf_allow_amount, "
	query = query & "SUM (mf.revenue_adjustment) AS mf_revenue_adjustment, "
	query = query & "SUM (mf.off_invoice_amount) AS mf_off_invoice_amount, "
	query = query & "0 AS ids_pounds_shipped, "
	query = query & "0 AS ids_indirect_sales_amount "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd1, "
	query = query & "tdw_owner.restated_market m1, "
	query = query & "tdw_owner.month_dim md1, "
	query = query & "tdw_owner.restated_product p1, "
	query = query & "tdw_owner.day_dim d1, "
	query = query & "tdw_owner.margin_fact mf, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE mf.restated_market_key = m1.restated_market_key "
	query = query & "AND mf.restated_product_key = p1.restated_product_key "
	query = query & "AND mf.restated_market_key = mpbd1.restated_market_key "
	query = query & "AND mf.restated_product_key = mpbd1.restated_product_key "
	query = query & "AND mf.invoice_day_key = d1.day_key "
	query = query & "AND d1.month_ending_date = md1.month_ending_date "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m1.DIVISION_CODE "
	query = query & "AND (mpbd1.business_division_code IN ('F01', 'F03', 'F04', 'F08', 'F15')) "
	query = query & "AND (m1.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md1.year_descr IN (:p_year)) "
	query = query & "and md1.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd1.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m1.division_code IN (:p_salesdivision)) "
	query = query & "AND (m1.region_code IN (:p_salesregion)) "
	query = query & "AND (m1.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER "
	query = query & "UNION "
	query = query & "SELECT   /*+ RULE */ "
	query = query & "mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER, "
	query = query & "0 AS mf_pounds_shipped, "
	query = query & "0 AS mf_adjusted_pounds_shipped, "
	query = query & "0 AS mf_gross_sales_amount, "
	query = query & "0 AS mf_allow_amount, "
	query = query & "0 AS mf_revenue_adjustment, "
	query = query & "0 AS mf_off_invoice_amount, "
	query = query & "SUM (ids.pounds_shipped) AS ids_pounds_shipped, "
	query = query & "SUM (ids.indirect_sales_amount)AS ids_indirect_sales_amount "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd1, "
	query = query & "tdw_owner.restated_market m1, "
	query = query & "tdw_owner.month_dim md1, "
	query = query & "tdw_owner.restated_product p1, "
	query = query & "tdw_owner.indirect_sales ids, "
	query = query & "tdw_owner.week_dim w1, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE ids.restated_market_key = m1.restated_market_key "
	query = query & "AND ids.restated_product_key = p1.restated_product_key "
	query = query & "AND ids.restated_market_key = mpbd1.restated_market_key "
	query = query & "AND ids.restated_product_key = mpbd1.restated_product_key "
	query = query & "AND ids.week_key = w1.week_key "
	query = query & "AND w1.month_ending_date = md1.month_ending_date "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m1.DIVISION_CODE "
	query = query & "AND (mpbd1.business_division_code IN ('F01', 'F03', 'F04', 'F08', 'F15')) "
	query = query & "AND (m1.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md1.year_descr IN (:p_year)) "
	query = query & "and md1.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd1.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m1.division_code IN (:p_salesdivision)) "
	query = query & "AND (m1.region_code IN (:p_salesregion)) "
	query = query & "AND (m1.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER "
	query = query & ")--end sub query "
	query = query & "   ids_mf, "
	query = query & "tdw_owner.restated_mkt_prd_bus_div_dim mpbd, "
	query = query & "tdw_owner.restated_market m, "
	query = query & "tdw_owner.restated_product p, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE ids_mf.restated_market_key = mpbd.restated_market_key "
	query = query & "AND ids_mf.restated_product_key = mpbd.restated_product_key "
	query = query & "AND ids_mf.restated_market_key = m.restated_market_key "
	query = query & "AND ids_mf.restated_product_key = p.restated_product_key "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m.DIVISION_CODE "
	query = query & "AND (mpbd.business_division_code IN ('F01', 'F03', 'F04', 'F08', 'F15')) "
	query = query & "AND (m.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (ids_mf.year_descr IN (:p_year)) "
	query = query & "and ids_mf.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m.division_code IN (:p_salesdivision)) "
	query = query & "AND (m.region_code IN (:p_salesregion)) "
	query = query & "AND (m.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY  "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "'zzz', "
	query = query & "mpbd.business_division_code, "
	query = query & "INITCAP (mpbd.business_division_descr), "
	query = query & "ids_mf.year_descr, "
	query = query & "ids_mf.month_descr, "
	query = query & "ids_mf.FISCAL_MONTH_NUMBER, "
	query = query & "mpbd.business_division_Descr "
	query = query & "--Begin Volume 'Total Value Added' "
	query = query & "UNION "
	query = query & "SELECT    "
	query = query & "'zzz' AS businessunit, "
	query = query & "0 AS monthexpense_amt, "
	query = query & "CASE WHEN (ids_mf.FISCAL_MONTH_NUMBER = (:p_Month)) "
	query = query & "     THEN SUM (  ids_mf.mf_pounds_shipped "
	query = query & "               + ids_mf.mf_adjusted_pounds_shipped "
	query = query & "               + ids_mf.ids_pounds_shipped) "
	query = query & "END AS monthpounds, "
	query = query & "CASE WHEN (ids_mf.FISCAL_MONTH_NUMBER = (:p_Month)) "
	query = query & "     THEN SUM (  ids_mf.mf_gross_sales_amount "
	query = query & "               - ids_mf.mf_allow_amount "
	query = query & "               - ids_mf.mf_off_invoice_amount "
	query = query & "                 + ids_mf.mf_revenue_adjustment "
	query = query & "               + ids_mf.ids_indirect_sales_amount) "
	query = query & "END AS monthnetreceivables, "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "'Total Value Added' AS businessdivisiondescr, "
	query = query & "NULL AS spend_base_descr, "
	query = query & "NULL AS spend_base_seq, "
	query = query & "NULL AS spend_subcategory_descr, "
	query = query & "NULL AS spend_subcategory_seq, "
	query = query & "ids_mf.year_descr, "
	query = query & "ids_mf.month_descr, "
	query = query & "0 AS expense_amt, "
	query = query & "SUM (  ids_mf.mf_pounds_shipped "
	query = query & "        + ids_mf.mf_adjusted_pounds_shipped "
	query = query & "        + ids_mf.ids_pounds_shipped "
	query = query & "        ) AS total_pounds_shipped, "
	query = query & "SUM (  ids_mf.mf_gross_sales_amount "
	query = query & "       - ids_mf.mf_allow_amount "
	query = query & "       - ids_mf.mf_off_invoice_amount "
	query = query & "       + ids_mf.mf_revenue_adjustment "
	query = query & "       + ids_mf.ids_indirect_sales_amount "
	query = query & "       ) AS net_receivable_dollar "
	query = query & "FROM ( "
	query = query & "--Begin sub query "
	query = query & "SELECT   mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER, "
	query = query & "SUM (mf.pounds_shipped) AS mf_pounds_shipped, "
	query = query & "SUM (mf.adj_pounds_shipped) AS mf_adjusted_pounds_shipped, "
	query = query & "SUM (mf.gross_sales_amount) AS mf_gross_sales_amount, "
	query = query & "SUM (mf.allow_amount) AS mf_allow_amount, "
	query = query & "SUM (mf.revenue_adjustment) AS mf_revenue_adjustment, "
	query = query & "SUM (mf.off_invoice_amount) AS mf_off_invoice_amount, "
	query = query & "0 AS ids_pounds_shipped, "
	query = query & "0 AS ids_indirect_sales_amount "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd1, "
	query = query & "tdw_owner.restated_market m1, "
	query = query & "tdw_owner.month_dim md1, "
	query = query & "tdw_owner.restated_product p1, "
	query = query & "tdw_owner.day_dim d1, "
	query = query & "tdw_owner.margin_fact mf, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE mf.restated_market_key = m1.restated_market_key "
	query = query & "AND mf.restated_product_key = p1.restated_product_key "
	query = query & "AND mf.restated_market_key = mpbd1.restated_market_key "
	query = query & "AND mf.restated_product_key = mpbd1.restated_product_key "
	query = query & "AND mf.invoice_day_key = d1.day_key "
	query = query & "AND d1.month_ending_date = md1.month_ending_date "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m1.DIVISION_CODE "
	query = query & "AND (mpbd1.business_division_code IN ('F01', 'F08', 'F15')) "
	query = query & "AND (m1.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md1.year_descr IN (:p_year)) "
	query = query & "and md1.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd1.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m1.division_code IN (:p_salesdivision)) "
	query = query & "AND (m1.region_code IN (:p_salesregion)) "
	query = query & "AND (m1.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER "
	query = query & "UNION "
	query = query & "SELECT   /*+ RULE */ "
	query = query & "mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER, "
	query = query & "0 AS mf_pounds_shipped, "
	query = query & "0 AS mf_adjusted_pounds_shipped, "
	query = query & "0 AS mf_gross_sales_amount, "
	query = query & "0 AS mf_allow_amount, "
	query = query & "0 AS mf_revenue_adjustment, "
	query = query & "0 AS mf_off_invoice_amount, "
	query = query & "SUM (ids.pounds_shipped) AS ids_pounds_shipped, "
	query = query & "SUM (ids.indirect_sales_amount)AS ids_indirect_sales_amount "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd1, "
	query = query & "tdw_owner.restated_market m1, "
	query = query & "tdw_owner.month_dim md1, "
	query = query & "tdw_owner.restated_product p1, "
	query = query & "tdw_owner.indirect_sales ids, "
	query = query & "tdw_owner.week_dim w1, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE ids.restated_market_key = m1.restated_market_key "
	query = query & "AND ids.restated_product_key = p1.restated_product_key "
	query = query & "AND ids.restated_market_key = mpbd1.restated_market_key "
	query = query & "AND ids.restated_product_key = mpbd1.restated_product_key "
	query = query & "AND ids.week_key = w1.week_key "
	query = query & "AND w1.month_ending_date = md1.month_ending_date "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m1.DIVISION_CODE "
	query = query & "AND (mpbd1.business_division_code IN ('F01', 'F08', 'F15')) "
	query = query & "AND (m1.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md1.year_descr IN (:p_year)) "
	query = query & "and md1.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd1.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m1.division_code IN (:p_salesdivision)) "
	query = query & "AND (m1.region_code IN (:p_salesregion)) "
	query = query & "AND (m1.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER "
	query = query & ") --end sub query "
	query = query & "   ids_mf, "
	query = query & "tdw_owner.restated_mkt_prd_bus_div_dim mpbd, "
	query = query & "tdw_owner.restated_market m, "
	query = query & "tdw_owner.restated_product p, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE ids_mf.restated_market_key = mpbd.restated_market_key "
	query = query & "AND ids_mf.restated_product_key = mpbd.restated_product_key "
	query = query & "AND ids_mf.restated_market_key = m.restated_market_key "
	query = query & "AND ids_mf.restated_product_key = p.restated_product_key "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m.DIVISION_CODE "
	query = query & "AND (mpbd.business_division_code IN ('F01', 'F08', 'F15')) "
	query = query & "AND (m.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (ids_mf.year_descr IN (:p_year)) "
	query = query & "and ids_mf.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m.division_code IN (:p_salesdivision)) "
	query = query & "AND (m.region_code IN (:p_salesregion)) "
	query = query & "AND (m.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY  "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "'zzz', "
	query = query & "mpbd.business_division_code, "
	query = query & "'Total Value Added', "
	query = query & "ids_mf.year_descr, "
	query = query & "ids_mf.month_descr, "
	query = query & "ids_mf.FISCAL_MONTH_NUMBER, "
	query = query & "mpbd.business_division_Descr "
	query = query & "---Begin Volume Total Market/CVP "
	query = query & "UNION "
	query = query & "SELECT    "
	query = query & "'zzz' AS businessunit, "
	query = query & "0 AS monthexpense_amt, "
	query = query & "CASE WHEN (ids_mf.FISCAL_MONTH_NUMBER = (:p_Month)) "
	query = query & "     THEN SUM (  ids_mf.mf_pounds_shipped "
	query = query & "               + ids_mf.mf_adjusted_pounds_shipped "
	query = query & "               + ids_mf.ids_pounds_shipped) "
	query = query & "END AS monthpounds, "
	query = query & "CASE WHEN (ids_mf.FISCAL_MONTH_NUMBER = (:p_Month)) "
	query = query & "     THEN SUM (  ids_mf.mf_gross_sales_amount "
	query = query & "                - ids_mf.mf_allow_amount "
	query = query & "                - ids_mf.mf_off_invoice_amount "
	query = query & "                + ids_mf.mf_revenue_adjustment "
	query = query & "                + ids_mf.ids_indirect_sales_amount) "
	query = query & "END AS monthnetreceivables, "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "'Total Market/CVP' AS businessdivisiondescr, "
	query = query & "NULL AS spend_base_descr, "
	query = query & "NULL AS spend_base_seq, "
	query = query & "NULL AS spend_subcategory_descr, "
	query = query & "NULL AS spend_subcategory_seq, "
	query = query & "ids_mf.year_descr, "
	query = query & "ids_mf.month_descr, "
	query = query & "0 AS expense_amt, "
	query = query & "SUM (  ids_mf.mf_pounds_shipped "
	query = query & "        + ids_mf.mf_adjusted_pounds_shipped "
	query = query & "        + ids_mf.ids_pounds_shipped "
	query = query & "        ) AS total_pounds_shipped, "
	query = query & "SUM (  ids_mf.mf_gross_sales_amount "
	query = query & "        - ids_mf.mf_allow_amount "
	query = query & "        - ids_mf.mf_off_invoice_amount "
	query = query & "        + ids_mf.mf_revenue_adjustment "
	query = query & "        + ids_mf.ids_indirect_sales_amount "
	query = query & ") AS net_receivable_dollar "
	query = query & "FROM ( "
	query = query & "---Begin sub query "
	query = query & "SELECT   mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER, "
	query = query & "SUM (mf.pounds_shipped) AS mf_pounds_shipped, "
	query = query & "SUM (mf.adj_pounds_shipped) AS mf_adjusted_pounds_shipped, "
	query = query & "SUM (mf.gross_sales_amount) AS mf_gross_sales_amount, "
	query = query & "SUM (mf.allow_amount) AS mf_allow_amount, "
	query = query & "SUM (mf.revenue_adjustment) AS mf_revenue_adjustment, "
	query = query & "SUM (mf.off_invoice_amount) AS mf_off_invoice_amount, "
	query = query & "0 AS ids_pounds_shipped, "
	query = query & "0 AS ids_indirect_sales_amount "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd1, "
	query = query & "tdw_owner.restated_market m1, "
	query = query & "tdw_owner.month_dim md1, "
	query = query & "tdw_owner.restated_product p1, "
	query = query & "tdw_owner.day_dim d1, "
	query = query & "tdw_owner.margin_fact mf, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE mf.restated_market_key = m1.restated_market_key "
	query = query & "AND mf.restated_product_key = p1.restated_product_key "
	query = query & "AND mf.restated_market_key = mpbd1.restated_market_key "
	query = query & "AND mf.restated_product_key = mpbd1.restated_product_key "
	query = query & "AND mf.invoice_day_key = d1.day_key "
	query = query & "AND d1.month_ending_date = md1.month_ending_date "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m1.DIVISION_CODE "
	query = query & "AND (mpbd1.business_division_code IN ('F03', 'F04')) "
	query = query & "AND (m1.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md1.year_descr IN (:p_year)) "
	query = query & "and md1.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd1.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m1.division_code IN (:p_salesdivision)) "
	query = query & "AND (m1.region_code IN (:p_salesregion)) "
	query = query & "AND (m1.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER "
	query = query & "UNION "
	query = query & "SELECT   /*+ RULE */ "
	query = query & "mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER, "
	query = query & "0 AS mf_pounds_shipped, "
	query = query & "0 AS mf_adjusted_pounds_shipped, "
	query = query & "0 AS mf_gross_sales_amount, "
	query = query & "0 AS mf_allow_amount, "
	query = query & "0 AS mf_revenue_adjustment, "
	query = query & "0 AS mf_off_invoice_amount, "
	query = query & "SUM (ids.pounds_shipped) AS ids_pounds_shipped, "
	query = query & "SUM (ids.indirect_sales_amount) "
	query = query & "                 AS ids_indirect_sales_amount "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd1, "
	query = query & "tdw_owner.restated_market m1, "
	query = query & "tdw_owner.month_dim md1, "
	query = query & "tdw_owner.restated_product p1, "
	query = query & "tdw_owner.indirect_sales ids, "
	query = query & "tdw_owner.week_dim w1, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE ids.restated_market_key = m1.restated_market_key "
	query = query & "AND ids.restated_product_key = p1.restated_product_key "
	query = query & "AND ids.restated_market_key = mpbd1.restated_market_key "
	query = query & "AND ids.restated_product_key = mpbd1.restated_product_key "
	query = query & "AND ids.week_key = w1.week_key "
	query = query & "AND w1.month_ending_date = md1.month_ending_date "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m1.DIVISION_CODE "
	query = query & "AND (mpbd1.business_division_code IN ('F03', 'F04')) "
	query = query & "AND (m1.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md1.year_descr IN (:p_year)) "
	query = query & "and md1.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd1.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m1.division_code IN (:p_salesdivision)) "
	query = query & "AND (m1.region_code IN (:p_salesregion)) "
	query = query & "AND (m1.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER "
	query = query & ")  ---End sub query "
	query = query & "   ids_mf, "
	query = query & "tdw_owner.restated_mkt_prd_bus_div_dim mpbd, "
	query = query & "tdw_owner.restated_market m, "
	query = query & "tdw_owner.restated_product p, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE ids_mf.restated_market_key = mpbd.restated_market_key "
	query = query & "AND ids_mf.restated_product_key = mpbd.restated_product_key "
	query = query & "AND ids_mf.restated_market_key = m.restated_market_key "
	query = query & "AND ids_mf.restated_product_key = p.restated_product_key "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m.DIVISION_CODE "
	query = query & "AND (mpbd.business_division_code IN ('F03', 'F04')) "
	query = query & "AND (m.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (ids_mf.year_descr IN (:p_year)) "
	query = query & "and ids_mf.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m.division_code IN (:p_salesdivision)) "
	query = query & "AND (m.region_code IN (:p_salesregion)) "
	query = query & "AND (m.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY  "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "'zzz', "
	query = query & "mpbd.business_division_code, "
	query = query & "'Total Market/CVP', "
	query = query & "ids_mf.year_descr, "
	query = query & "ids_mf.month_descr, "
	query = query & "ids_mf.FISCAL_MONTH_NUMBER, "
	query = query & "mpbd.business_division_Descr "
	query = query & "---Begin Volume Total customer "
	query = query & "UNION "
	query = query & "SELECT    "
	query = query & "'zzz' AS businessunit, "
	query = query & "0 AS monthexpense_amt, "
	query = query & "CASE WHEN (ids_mf.FISCAL_MONTH_NUMBER = (:p_Month)) "
	query = query & "     THEN SUM (  ids_mf.mf_pounds_shipped "
	query = query & "               + ids_mf.mf_adjusted_pounds_shipped "
	query = query & "               + ids_mf.ids_pounds_shipped) "
	query = query & "END AS monthpounds, "
	query = query & "CASE WHEN (ids_mf.FISCAL_MONTH_NUMBER = (:p_Month)) "
	query = query & "     THEN SUM (  ids_mf.mf_gross_sales_amount "
	query = query & "                - ids_mf.mf_allow_amount "
	query = query & "                - ids_mf.mf_off_invoice_amount "
	query = query & "                + ids_mf.mf_revenue_adjustment "
	query = query & "                + ids_mf.ids_indirect_sales_amount) "
	query = query & "END AS monthnetreceivables, "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "mpbd.business_division_code, "
	query = query & "'Total Customer' AS businessdivisiondescr, "
	query = query & "NULL AS spend_base_descr, "
	query = query & "NULL AS spend_base_seq, "
	query = query & "NULL AS spend_subcategory_descr, "
	query = query & "NULL AS spend_subcategory_seq, "
	query = query & "ids_mf.year_descr, "
	query = query & "ids_mf.month_descr, "
	query = query & "0 AS expense_amt, "
	query = query & "SUM (  ids_mf.mf_pounds_shipped "
	query = query & "       + ids_mf.mf_adjusted_pounds_shipped "
	query = query & "       + ids_mf.ids_pounds_shipped "
	query = query & "      ) AS total_pounds_shipped, "
	query = query & "SUM (  ids_mf.mf_gross_sales_amount "
	query = query & "     - ids_mf.mf_allow_amount "
	query = query & "     - ids_mf.mf_off_invoice_amount "
	query = query & "     + ids_mf.mf_revenue_adjustment "
	query = query & "     + ids_mf.ids_indirect_sales_amount "
	query = query & "     ) AS net_receivable_dollar "
	query = query & "FROM ( "
	query = query & "---Begin sub query "
	query = query & "SELECT   mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER, "
	query = query & "SUM (mf.pounds_shipped) AS mf_pounds_shipped, "
	query = query & "SUM (mf.adj_pounds_shipped) AS mf_adjusted_pounds_shipped, "
	query = query & "SUM (mf.gross_sales_amount) AS mf_gross_sales_amount, "
	query = query & "SUM (mf.allow_amount) AS mf_allow_amount, "
	query = query & "SUM (mf.revenue_adjustment) AS mf_revenue_adjustment, "
	query = query & "SUM (mf.off_invoice_amount) AS mf_off_invoice_amount, "
	query = query & "0 AS ids_pounds_shipped, "
	query = query & "0 AS ids_indirect_sales_amount "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd1, "
	query = query & "tdw_owner.restated_market m1, "
	query = query & "tdw_owner.month_dim md1, "
	query = query & "tdw_owner.restated_product p1, "
	query = query & "tdw_owner.day_dim d1, "
	query = query & "tdw_owner.margin_fact mf, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE mf.restated_market_key = m1.restated_market_key "
	query = query & "AND mf.restated_product_key = p1.restated_product_key "
	query = query & "AND mf.restated_market_key = mpbd1.restated_market_key "
	query = query & "AND mf.restated_product_key = mpbd1.restated_product_key "
	query = query & "AND mf.invoice_day_key = d1.day_key "
	query = query & "AND d1.month_ending_date = md1.month_ending_date "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m1.DIVISION_CODE "
	query = query & "AND (mpbd1.business_division_code IN ('F01', 'F03', 'F04', 'F08', 'F15')) "
	query = query & "AND (m1.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md1.year_descr IN (:p_year)) "
	query = query & "and md1.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd1.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m1.division_code IN (:p_salesdivision)) "
	query = query & "AND (m1.region_code IN (:p_salesregion)) "
	query = query & "AND (m1.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER "
	query = query & "UNION "
	query = query & "SELECT   /*+ RULE */ "
	query = query & "mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER, "
	query = query & "0 AS mf_pounds_shipped, "
	query = query & "0 AS mf_adjusted_pounds_shipped, "
	query = query & "0 AS mf_gross_sales_amount, "
	query = query & "0 AS mf_allow_amount, "
	query = query & "0 AS mf_revenue_adjustment, "
	query = query & "0 AS mf_off_invoice_amount, "
	query = query & "SUM (ids.pounds_shipped) AS ids_pounds_shipped, "
	query = query & "SUM (ids.indirect_sales_amount) "
	query = query & "                 AS ids_indirect_sales_amount "
	query = query & "FROM tdw_owner.restated_mkt_prd_bus_div_dim mpbd1, "
	query = query & "tdw_owner.restated_market m1, "
	query = query & "tdw_owner.month_dim md1, "
	query = query & "tdw_owner.restated_product p1, "
	query = query & "tdw_owner.indirect_sales ids, "
	query = query & "tdw_owner.week_dim w1, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE ids.restated_market_key = m1.restated_market_key "
	query = query & "AND ids.restated_product_key = p1.restated_product_key "
	query = query & "AND ids.restated_market_key = mpbd1.restated_market_key "
	query = query & "AND ids.restated_product_key = mpbd1.restated_product_key "
	query = query & "AND ids.week_key = w1.week_key "
	query = query & "AND w1.month_ending_date = md1.month_ending_date "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m1.DIVISION_CODE "
	query = query & "AND (mpbd1.business_division_code IN ('F01', 'F03', 'F04', 'F08', 'F15')) "
	query = query & "AND (m1.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (md1.year_descr IN (:p_year)) "
	query = query & "and md1.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd1.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m1.division_code IN (:p_salesdivision)) "
	query = query & "AND (m1.region_code IN (:p_salesregion)) "
	query = query & "AND (m1.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY mpbd1.business_division_code, "
	query = query & "mpbd1.business_division_descr, "
	query = query & "mpbd1.restated_market_key, "
	query = query & "mpbd1.restated_product_key, "
	query = query & "md1.year_descr, "
	query = query & "md1.month_descr, "
	query = query & "md1.FISCAL_MONTH_NUMBER "
	query = query & ")   --end sub query "
	query = query & "   ids_mf, "
	query = query & "tdw_owner.restated_mkt_prd_bus_div_dim mpbd, "
	query = query & "tdw_owner.restated_market m, "
	query = query & "tdw_owner.restated_product p, "
	query = query & "tdw_owner.group_detail gd, "
	query = query & "tdw_owner.group_description groupdescr "
	query = query & "WHERE ids_mf.restated_market_key = mpbd.restated_market_key "
	query = query & "AND ids_mf.restated_product_key = mpbd.restated_product_key "
	query = query & "AND ids_mf.restated_market_key = m.restated_market_key "
	query = query & "AND ids_mf.restated_product_key = p.restated_product_key "
	query = query & "AND gd.GROUP_CODE = groupdescr.GROUP_CODE "
	query = query & "AND gd.group_field_c  =  m.DIVISION_CODE "
	query = query & "AND (mpbd.business_division_code IN ('F01', 'F03', 'F04', 'F08', 'F15')) "
	query = query & "AND (m.selling_group_code IN ('119000', '125000', '610000', '800000', '423000')) "
	query = query & "AND (ids_mf.year_descr IN (:p_year)) "
	query = query & "and ids_mf.fiscal_month_number <= :p_Month "
	query = query & "AND (mpbd.business_division_code IN (:p_businessdivision)) "
	query = query & "AND (m.division_code IN (:p_salesdivision)) "
	query = query & "AND (m.region_code IN (:p_salesregion)) "
	query = query & "AND (m.primary_broker_code IN (:p_primarybroker)) "
	query = query & "AND gd.GROUP_CODE in (:vp) "
	query = query & "GROUP BY  "

	If (grouping = "VP") Then
		query = query & "gd.GROUP_CODE, "
		query = query & "groupdescr.GROUP_DESCR, "
	Else If (grouping = "DOS")
		query = query & "m.DIVISION_CODE, "
		query = query & "m.DIVISION_DESCR, "
	Else If (grouping = "RSM")
		query = query & "m.REGION_CODE, "
		query = query & "m.REGION_DESCR, "
	End If

	query = query & "'zzz', "
	query = query & "mpbd.business_division_code, "
	query = query & "'Total Customer', "
	query = query & "ids_mf.year_descr, "
	query = query & "ids_mf.month_descr, "
	query = query & "ids_mf.FISCAL_MONTH_NUMBER, "
	query = query & "mpbd.business_division_Descr "
	query = query & "ORDER BY businessdivisiondescr, spend_base_seq, spend_subcategory_seq"
	
	replace(query, ":p_Month", month)
	replace(query, ":p_year", year)
	replace(query, ":p_businessdivision", bd)
	replace(query, ":p_salesdivision", sd)
	replace(query, ":p_salesregion", sr)
	replace(query, ":p_primarybroker", pb)
	replace(query, ":vp", vp)
End Function