SELECT 
       substr(SSF.REPORT_PARAM_STREAM,
              instr(SSF.REPORT_PARAM_STREAM,'!',1,1)+1,
              instr(SSF.REPORT_PARAM_STREAM,'!',1,2)-instr(SSF.REPORT_PARAM_STREAM,'!',1,1)-1) as REPORT_LEVEL,
	   SSF.SUBSCRIPTION_NAME,
	   SSF.FILE_NAME,
       SSF.FILE_PATH PATH,
       SSF.RENDER_FRMT RENDER_FORMAT,
       SSF.WRITE_MODE,
       SSF.APPEND_FILE_EXT FILE_EXTENSION,
       SSF.FILE_ACCESS_NAME USER_NAME,
       SSF.FILE_PARAM PASSWORD,
       substr(report_param_stream,
              instr(SSF.REPORT_PARAM_STREAM,'!',1,2)+1,
              instr(SSF.REPORT_PARAM_STREAM,'!',1,3)-instr(SSF.REPORT_PARAM_STREAM,'!',1,2)-1) as PERIOD_COMPARISON
  FROM DWA_OWNER.SSRS_SUBSCRIPTION_FILE SSF
 WHERE SSF.ACTIVE_FLAG = 'Y'
     AND SSF.SUBSCRIPTION_NAME = 'FINSQ1CFS'