ALTER DATABASE TRA_MART_MSS ADD FILE ( NAME = 'FGAOD3602',
                             FILENAME = 'G:\TRA_MSSS_DATA\TRA_MART_MSS_AOD_FG\FGAOD3602.ndf',
                             SIZE = 50MB, FILEGROWTH = 10MB) TO FILEGROUP FGAOD3602
                             
ALTER PARTITION SCHEME ps_FACT_ORDER_ADD_ON_DEMAND NEXT USED FGAOD3602
ALTER PARTITION FUNCTION pf_FACT_ORDER_ADD_ON_DEMAND  () SPLIT RANGE (3602)



/* Fact order addon demand */
//call PredictTheFuture.RunSQLQuery('WHQWTRA01', 'TRA_MART_MSS', 'ALTER DATABASE TRA_MART_MSS ADD FILE ( NAME = ''FGDSIFCST3601'', FILENAME = ''G:\TRA_MSSS_DATA\TRA_MART_MSS_AOD_FG\FGAOD3602.ndf'',SIZE = 50MB, FILEGROWTH = 10MB) TO FILEGROUP FGAOD3602')
//call PredictTheFuture.RunSQLQuery('WHQWTRA01', 'TRA_MART_MSS', 'ALTER PARTITION SCHEME ps_FACT_ORDER_ADD_ON_DEMAND NEXT USED FGAOD3602')
//call PredictTheFuture.RunSQLQuery('WHQWTRA01', 'TRA_MART_MSS', 'ALTER PARTITION FUNCTION pf_FACT_ORDER_ADD_ON_DEMAND  () SPLIT RANGE (3602)')


/* DSI Forecast */
//call PredictTheFuture.RunSQLQuery('WHQWTRA01', 'TRA_MART_MSS', 'ALTER DATABASE TRA_MART_MSS ADD FILE ( NAME = ''FGDSIFCST3601'',FILENAME = ''G:\TRA_MSSS_DATA\TRA_MART_MSS_DSI_FG\FGDSIFCST3601.ndf'',SIZE = 100MB, FILEGROWTH = 10MB) TO FILEGROUP FGDSIFCST3601')

//call PredictTheFuture.RunSQLQuery('WHQWTRA01', 'TRA_MART_MSS', 'ALTER PARTITION SCHEME ps_FACT_DAILY_STORE_ITEM_FORECAST NEXT USED ''FGDSIFCST3601''')

//call PredictTheFuture.RunSQLQuery('WHQWTRA01', 'TRA_MART_MSS', 'ALTER PARTITION FUNCTION pf_FACT_DAILY_STORE_ITEM_FORECAST  () SPLIT RANGE (''3601'')')
