/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000
       UD.USERID
      ,SD.DATE_DISPLAY
      ,ST.TIME_DISPLAY_12
      ,ED.DATE_DISPLAY
      ,ET.TIME_DISPLAY_12
      ,OD.OBJECT_NAME
      ,[QUERY_SUCCESS_IND]
      ,[EXECUTE_TIME_SEC_QTY]
      ,QD.QUERY_TEXT
  FROM [SSASLogging].[dbo].[QUERY_FACT] QF
  INNER JOIN DATE_DIM SD
	ON QF.START_DATE_KEY = SD.DATE_KEY
  INNER JOIN DATE_DIM ED
	ON QF.END_DATE_KEY = ED.DATE_KEY
  INNER JOIN USER_DIM UD
	ON QF.USER_KEY = UD.USER_KEY
  INNER JOIN DB_OBJECT_DIM OD
	ON QF.OBJECT_KEY = OD.OBJECT_KEY
  INNER JOIN QUERY_DIM QD
	ON QF.QUERY_KEY = QD.QUERY_KEY
  INNER JOIN TIME_DIM ST
	ON QF.START_TIME_KEY = ST.TIME_KEY
  INNER JOIN TIME_DIM ET
	ON QF.END_TIME_KEY = ET.TIME_KEY
  WHERE 
	--UD.USERID = 'MILLERBARR'
	UD.USERID = 'FRITTSE'
	AND OD.SERVER_NAME = 'WHQWSSAS02'
	--AND SD.DATE = '2011-09-08'
  ORDER BY SD.DATE DESC
  
  
SELECT TOP 1000
	 AD.AGGREGATION_NAME,
	 AD.AGGREGATION_PATH,
	 AD.AGGREGATION_DEF,
	 UD.USERID,
	 DD.DATE_DISPLAY,
	 TD.TIME_DISPLAY_12,
	 OD.OBJECT_NAME,
	 AF.AGGREGATION_COUNT
FROM 
	[SSASLogging].[dbo].[AGGREGATION_FACT] AF
INNER JOIN AGGREGATION_DIM AD
	ON AF.AGGREGATION_KEY = AD.AGGREGATION_KEY
INNER JOIN USER_DIM UD
	ON AF.USER_KEY = UD.USER_KEY
INNER JOIN DATE_DIM DD
	ON AF.DATE_KEY = DD.DATE_KEY
INNER JOIN TIME_DIM TD
	ON AF.TIME_KEY = TD.TIME_KEY
INNER JOIN DB_OBJECT_DIM OD
	ON AF.OBJECT_KEY = OD.OBJECT_KEY
WHERE 
	--UD.USERID = 'MILLERBARR'
	UD.USERID = 'FRITTSE'
	AND OD.SERVER_NAME = 'WHQWSSAS02'
	--AND DD.DATE = '2011-09-08'
	AND AGGREGATION_PATH like '%Tyson Retail Analytics%'
ORDER BY DD.DATE DESC
  