USE [master]
GO
ALTER DATABASE [TRA_MART_MSS] ADD FILEGROUP [FGRLOCURRENT]
GO
ALTER DATABASE [TRA_MART_MSS] ADD FILEGROUP [FGRLONOTCURRENT]
GO
ALTER DATABASE [TRA_MART_MSS] ADD FILEGROUP [FGRLOOLD]
GO

USE [master]
GO
ALTER DATABASE [TRA_MART_MSS] ADD FILE ( NAME = N'FGRLOCURRENT', FILENAME = N'G:\TRA_MSSS_DATA\TRA_MART_MSS_RLO_FG\FGRLOCURRENT.ndf' , SIZE = 5120KB , FILEGROWTH = 51200KB ) TO FILEGROUP [FGRLOCURRENT]
GO
ALTER DATABASE [TRA_MART_MSS] ADD FILE ( NAME = N'FGRLONOTCURRENT', FILENAME = N'G:\TRA_MSSS_DATA\TRA_MART_MSS_RLO_FG\FGRLONOTCURRENT.ndf' , SIZE = 5120KB , FILEGROWTH = 51200KB ) TO FILEGROUP [FGRLONOTCURRENT]
GO
ALTER DATABASE [TRA_MART_MSS] ADD FILE ( NAME = N'FGRLOOLD', FILENAME = N'G:\TRA_MSSS_DATA\TRA_MART_MSS_RLO_FG\FGRLOOLD.ndf' , SIZE = 5120KB , FILEGROWTH = 51200KB ) TO FILEGROUP [FGRLOOLD]
GO


USE [TRA_MART_MSS]
GO

/****** Object:  PartitionFunction [pf_FACT_OP_SO_LINE]    Script Date: 02/23/2012 14:35:35 ******/
CREATE PARTITION FUNCTION [pf_FACT_RL_GROC_PO](varchar(30)) AS RANGE LEFT FOR VALUES (N'Current', N'Not Current')
GO


USE [TRA_MART_MSS]
GO

/****** Object:  PartitionScheme [ps_FACT_OP_SO_LINE]    Script Date: 02/23/2012 14:38:15 ******/
CREATE PARTITION SCHEME [ps_FACT_RL_GROC_PO] AS PARTITION [pf_FACT_RL_GROC_PO] TO ([FGRLOCURRENT], [FGRLONOTCURRENT], [FGRLOOLD])
GO



USE [TRA_MART_MSS]
GO
CREATE CLUSTERED INDEX [FACT_RL_GROC_PO_PK] ON [dbo].[FACT_RL_GROC_PO] 
(
      [RL_GROC_PO_CURRENT_IND] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [ps_FACT_RL_GROC_PO]([RL_GROC_PO_CURRENT_IND])
GO




